changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - duplicate
      - question
      - invalid
      - wontfix
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: 🚀 New Features
      labels:
        - feature
        - enhancement
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - chore
        - refactor
        - cleanup
    - title: 🏗️ Build & CI
      labels:
        - build
        - ci
        - github-actions
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🔄 Other Changes
      labels:
        - "*"
